name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Déclenche l'action sur un push vers la branche 'main', ajustez selon vos besoins
    tags:
      - 'v*'  # Déclenche l'action pour les tags, par exemple "v1.0", "v1.1" etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          # Récupérer le tag actuel, soit 'latest' soit le tag Git
          TAG=${GITHUB_REF#refs/tags/}
          if [ "$TAG" == "main" ]; then
            TAG="latest"
          fi
          docker build -t ${{ secrets.DOCKER_USERNAME }}/meteo-app:$TAG .

      - name: Push Docker image
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          if [ "$TAG" == "main" ]; then
            TAG="latest"
          fi
          docker push ${{ secrets.DOCKER_USERNAME }}/meteo-app:$TAG
