name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'  # Capture les tags comme v1.0.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          # Vérifier si c'est un tag, sinon utiliser 'latest'
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          else
            TAG="latest"
          fi
          docker build -t ${{ secrets.DOCKER_USERNAME }}/meteo-app:$TAG .

      - name: Push Docker image
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          else
            TAG="latest"
          fi
          docker push ${{ secrets.DOCKER_USERNAME }}/meteo-app:$TAG
